inherits = "solarized_dark"

"ui.background" = "black"
"ui.background.separator" = "base01"
"ui.help" = "blue"
"ui.linenr" = "base01"
"ui.menu" = "blue"
"ui.menu.selected" = "white"
"ui.popup.info" = "blue"
"ui.statusline" = "base01"
"ui.text" = "base1"
"ui.text.focus" = "blue"
"ui.text.info" = "blue"
"diagnostic.error" = "red"

"warning" = { fg = "yellow", modifiers = ["bold", "underlined"] }
"error" = { fg = "red", modifiers = ["bold", "underlined"] }
"info" = { fg = "blue", modifiers = ["bold", "underlined"] }
"hint" = { fg = "base01", modifiers = ["bold", "underlined"] }
